- pipeline.id: app_logs
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  pipeline.workers: 2
  pipeline.batch.size: 512
  queue.type: persisted
  path.queue: "/usr/share/logstash/data/queue"
  queue.max_bytes: 1024mb

